services:
  - type: web
    name: att-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
     
      - key: JWT_SECRET
        
      - key: EMAIL_USER
         
      - key: EMAIL_APP_PASS
        

  - type: static
    name: att-frontend
    rootDir: frontend/react
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: att-backend
          type: web
          property: url

